apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demoapp
        image: shivakiran/demo-app:1.0
        ports:
        - containerPort: 3000
